// react-entree/src/components/Header.jsx
import React, { useState } from 'react';
//import { useNavigate } from 'react-router-dom';
import logo from './images/logo.png';
import loginIcon from './images/log-in.svg';
import bookmarkIcon from './images/bookmark.svg';
import cartIcon from './images/shopping-cart.svg';
import '../css/Header.css';

const HeaderComponent = () => {
  //const navigate = useNavigate();
  const [isVisible, setIsVisible] = useState(false);
  const [count, setCount] = useState(0);

  const login = () => {
    if (localStorage.getItem("id") !== undefined) {
      localStorage.clear();
      //navigate('/');
      alert("Logout Successful!!");
    } else {
      //navigate('/login');
    }
  };

  const openCart = () => {
    //navigate('/cart');
  };

  const openButton = () => {
    setIsVisible(true);
  };

  const closeButton = () => {
    setIsVisible(false);
  };

  const increase = () => {
    setCount(prevCount => prevCount + 1);
  };

  const decrease = () => {
    setCount(prevCount => (prevCount > 0 ? prevCount - 1 : 0));
  };

  return (
    <header id="header">
      <div className="container-fluid topbar">
        <nav className="container d-flex justify-content-between pt-2 pb-2">
          
          <a className="navbar-brand" href="/#">
            <img src={logo} alt="Logo" width="150" height="50" />
          </a>

          <div id="searchdiv" className="d-none d-sm-none d-md-flex">

            <input type="search" name="search" id="searchbar" placeholder="What can we help you Find?" />
          </div>

          <div id="iconsdiv" className="iconsdiv">

            <a href="/#" onClick={login}>
              <img src={loginIcon} alt="icon" width="40" height="20" />
            </a>

            <a href="/wishlist">
              <img src={bookmarkIcon} alt="icon" width="40" height="20" />
            </a>

            <a href="/#" onClick={openCart}>
              <img src={cartIcon} alt="icon" width="40" height="20" />
            </a>
            
          </div>
        </nav>
      </div>
      <nav className="navbar navbar-expand-md" id="menu">
        <button className="navbar-toggler toggler_btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar" aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle Navigation">
          <span className="navbar-toggler-icon custom-toggler"></span>
        </button>
        <div className="collapse navbar-collapse" id="collapsibleNavbar">
          <ul className="navbar-nav me-auto m-3 m-md-0 mb-lg-0 nav-list">
            <li className="nav-item">
              <a className="nav-link" href="#recommend">RECOMMENDATION</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#topcat">TOP CATEGORY</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#newitems">NEW ITEMS</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#itemleft">ITEMS LEFT</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href="#exclusivebrands">EXCLUSIVE BRANDS</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
  );
};

export default HeaderComponent;

// entree-app/src/app/header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { WishlistComponent } from '../wishlist/wishlist.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})

export class HeaderComponent {

  constructor(private _router:Router){

  }
  isVisible = false;
  login(){
    if(localStorage.getItem("id")!=undefined){
      localStorage.clear();
      this._router.navigateByUrl('');
      alert("Logout Successful!!")
    }
    else{
      this._router.navigateByUrl('login');
    }
  }
 
  openCart(){
    this._router.navigateByUrl('cart');
  }
  openButton() {
    this.isVisible = true;
  }

  closeButton() {
    this.isVisible = false;
  }

  count:number = 0;
  increase(){
    this.count++;
  }
  decrease(){
    if(this.count > 0 ){
      this.count--;
    }
   
  }
}

<div class="cart" id="cart" *ngIf="isVisible">
  <div class="h4_cart">
    <h4 class="">Shopping cart</h4>
    <button
      type="button"
      class="btn-close"
      id="btn-close"
      aria-label="Close"
      (click)="closeButton()"
    ></button>
  </div>
  <div class="container container_cart">
    <div class="tiles_cart">
      <img
        src="../../assets/login.jpg"
        width="70px"
        height="80px"
        style="cursor: pointer"
      />

      <div class="cartitems">
        <div>
          <h5>Orange</h5>
          <h6>Price : $ 20</h6>
        </div>
        <div>
          <p class="count_cart">
            <span
              ><img
                src="../../assets/minus.png"
                width="20px"
                style="cursor: pointer"
                (click)="decrease()"
            /></span>
            {{ count }}
            <span
              ><img
                src="../../assets/plus.png"
                width="20px"
                style="cursor: pointer"
                (click)="increase()"
            /></span>
          </p>
        </div>
      </div>

      <button
        type="button"
        class="btn-close"
        id="remove_cart"
        aria-label="Close"
      ></button>
    </div>

    <div class="tiles_cart">
      <img
        src="../../assets/login.jpg"
        width="70px"
        height="80px"
        style="cursor: pointer"
      />

      <div class="cartitems">
        <div>
          <h5>Orange</h5>
          <h6>Price : $ 20</h6>
        </div>
        <div>
          <p class="count_cart">
            <span
              ><img
                src="../../assets/minus.png"
                width="20px"
                style="cursor: pointer"
                (click)="decrease()"
            /></span>
            {{ count }}
            <span
              ><img
                src="../../assets/plus.png"
                width="20px"
                style="cursor: pointer"
                (click)="increase()"
            /></span>
          </p>
        </div>
      </div>

      <button
        type="button"
        class="btn-close"
        id="remove_cart"
        aria-label="Close"
      ></button>
    </div>
    <div class="tiles_cart">
      <img
        src="../../assets/login.jpg"
        width="70px"
        height="80px"
        style="cursor: pointer"
      />

      <div class="cartitems">
        <div>
          <h5>Orange</h5>
          <h6>Price : $ 20</h6>
        </div>
        <div>
          <p class="count_cart">
            <span
              ><img
                src="../../assets/minus.png"
                width="20px"
                style="cursor: pointer"
                (click)="decrease()"
            /></span>
            {{ count }}
            <span
              ><img
                src="../../assets/plus.png"
                width="20px"
                style="cursor: pointer"
                (click)="increase()"
            /></span>
          </p>
        </div>
      </div>

      <button
        type="button"
        class="btn-close"
        id="remove_cart"
        aria-label="Close"
      ></button>
    </div>
    
    <div class="btn_parent">
      <button class="btn cart_btn_checkout">Checkout</button>
    </div>



  </div>
</div>

<header id="header">
     <div class="container-fluid topbar">
        <nav class=" container d-flex justify-content-between pt-2 pb-2">
    
          <a class="navbar-brand" href="#">
            <img src="../../assets/logo.png" alt="Logo" width="150" height="50" class="">
          </a>
    
    
          <div id="searchdiv" class="d-none d-sm-none d-md-flex">
           
            <input type="search" name="search" id="searchbar" placeholder="What can we help you Find?" class="" />
          </div>
    
    
    
          <div id="iconsdiv bg-success" class="iconsdiv">
            <a routerLink="/login"><img src="../../assets/log-in.svg" alt="icon" width="40" height="20" class=""></a>
            <a href=""><img src="../../assets/bell.svg" alt="icon" width="40" height="20" class=""></a>
            <a href=""><img src="../../assets/shopping-cart.svg" alt="icon" width="40" height="20" class="" (click)="openButton()"></a>
    
          </div>
    
    
        </nav>
      </div>
    
      <nav class="navbar navbar-expand-md" id="menu">
        <button class="navbar-toggler toggler_btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar" aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle Navigation">
          <span class="navbar-toggler-icon custom-toggler"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav me-auto m-3 m-md-0 mb-lg-0 nav-list">
            <li class="nav-item">
              <a class="nav-link" href="#recommend">RECOMMENDATION</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#topcat">TOP CATEGORY</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#newitems">NEW ITEMS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#itemleft">ITEMS LEFT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#exclusivebrands">EXCLUSIVE BRANDS</a>
            </li>
          </ul>
            
            
        </div>
      </nav>

</header>
