// entree-app/src/app/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  
  constructor(private _http:HttpClient,private _router:Router){

  }
  signup(){
this._router.navigateByUrl('/signup');
  }

}

<div class="container">
    <div class="logincard ">
    
      <div class="loginform">
        <h1>Login</h1>
        <div class="m-5 d-flex justify-content-center   ">
          <form class=" w-75">
           
            <div class="row mb-3">
              <div>
                <label class="form-label fs-6" for="email" >Email  </label>
                <input
                  type="text"
                  id="email"
                  class="form-control form-control"
                  [(ngModel)]="email"
                  name="email"
                  placeholder="Enter Your Email"
                  required
                />
              </div>
            </div>
  
          
  
            <div class="row mb-3">
              <div>
                <label class="form-label fs-6" for="password">Password</label>
                <input
                  type="password"
                  id="password"
                  class="form-control form-control"
                  [(ngModel)]="password"
                  name="password"
                  placeholder="Enter Your Password"
                  required
                />
              </div>
            </div>
            
         
  
            <div class="button  fs-2 mt-4">
              <button type="submit" class="btn btn-success w-25" (click)="login()">Login</button>
            </div>
  
            <div class="row mt-4 ">
              <p class="reg_para"> Forgot Password ?  <a routerLink="/forgetpassword" class="" > Click here  </a></p>
           <p class="reg_para"> New User ?  <a routerLink="/signup" class="" > Signup  </a></p>
            </div>
         
          </form>
        </div>
      </div>

      <div class="loginimage ">
        <img src="../../assets/login.jpg" alt="image"  />
      </div>
      
    </div>
  </div>

// react-entree/src/components/Login.jsx
import React from 'react'
import '../css/Login.css'
import login from '../images/login.jpg'

function Login() {
  return (
    <div className='container'>
      <div className='logincard'>
        <div className='loginform'>
        <h1>Login</h1>
        <div className='m-5 d-flex justify-content-center   '>
        <form class=" w-75">
           
           <div class="row mb-3">
             <div>
               <label class="form-label fs-6" for="email" >Email  </label>
               <input
                 type="text"
                 id="email"
                 class="form-control form-control"
                 name="email"
                 placeholder="Enter Your Email"
                 required
               />
             </div>
           </div>
 
         
 
           <div class="row mb-3">
             <div>
               <label class="form-label fs-6" for="password">Password</label>
               <input
                 type="password"
                 id="password"
                 class="form-control form-control"
                 name="password"
                 placeholder="Enter Your Password"
                 required/>
             </div>
           </div>
           
           <div class="button  fs-2 mt-4">
             <button type="submit" class="btn btn-success w-25">Login</button>
           </div>
 
           <div class="row mt-4 ">
             <p class="reg_para"> Forgot Password ?  <a routerLink="/forgetpassword" class="" > Click here  </a></p>
          <p class="reg_para"> New User ?  <a routerLink="/signup" class="" > Register  </a></p>
           </div>
         </form>
        </div>
      
        </div>
      <div className='loginimage'>
        <img src={login} alt="image"  />
      </div>
    </div>
    </div>
  )
}

export default Login;
